In [12]:
from setfit import SetFitModel, SetFitHead

In [3]:
model = SetFitModel.from_pretrained("./디자인-2000.pt").to('cuda')

In [39]:
model(['나는 이 디자인이 마음에 들어 ㅋㅋ', '근데 이거 맞냐?ㅋㅋㅋ', '여기 레스토랑 서비스가 영~', 'zara 옷들이 좀 예쁘긴하지', '이 음식 가격 이상해 ㅋ'])

tensor([1., 0., 0., 1., 0.], dtype=torch.float64)

In [40]:
probs = model.predict_proba(['나는 이 디자인이 마음에 들어 ㅋㅋ', '근데 이거 맞냐?ㅋㅋㅋ', '여기 레스토랑 서비스가 영~', 'zara 옷들이 좀 예쁘긴하지', '이 음식 가격 이상해 ㅋ'])
probs

tensor([[6.1285e-05, 9.9994e-01],
        [9.9994e-01, 5.5435e-05],
        [9.9995e-01, 4.9153e-05],
        [6.1729e-05, 9.9994e-01],
        [9.9995e-01, 4.9404e-05]], dtype=torch.float64)

In [28]:
probs.shape

torch.Size([5, 2])

In [29]:
indices = probs.argmax(axis=1)
indices

tensor([1, 0, 0, 1, 1])

In [31]:
threshold = 0.55
threshold_indices = [indices[i] if prob[indices[i]] > threshold else abs(indices[i]-1) for i, prob in enumerate(probs)]
threshold_indices

[tensor(1), tensor(0), tensor(0), tensor(1), tensor(1)]

In [41]:
import torch
torch.tensor(threshold_indices).tolist()

[1, 0, 0, 1, 1]